version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
          - push
          - release
    payload:
      maxRunTime: 3600
      image: jimmycuadra/rust
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          curl https://sh.rustup.rs -sSf | sh && . ~/.cargo/env &&
          git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} &&
          cargo test
    metadata:
      name: mp4parse
      description: Run cargo test for the mp4parse crates
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
