version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
          - push
          - release
    payload:
      maxRunTime: 3600
      image: jimmycuadra/rust
      command: []
    metadata:
      name: mp4parse
      description: Run cargo test for the mp4parse crates
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
