language: rust
rust:
  - stable
  - nightly
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - $CXX --version
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
