language: rust
rust:
  - stable
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

env:
  global:
    - CXX=g++-5

script:
  - cargo build --verbose
  - cargo test --verbose
  - make -C examples

before_deploy:
  - cargo doc

deploy:
  provider: surge
  project: ./target/doc/
  domain: mp4parse-docs.surge.sh
  on: surge-docs
