language: rust
rust:
  - stable
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

env:
  global:
    - CXX=g++-5

script:
  - (cd mp4parse && cargo test --verbose)
  - (cd mp4parse_capi && cargo test --verbose)
  - make -C mp4parse_capi/examples check
  - (cd mp4parse_capi && cargo doc)

deploy:
  provider: surge
  project: ./mp4parse_capi/target/doc/
  domain: mp4parse-docs.surge.sh
  skip_cleanup: true
