language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - g++ --version
  - uname -a
  - cat /etc/issue
  - cat /etc/apt/sources.list
install:
  - echo CXX = $CXX
  - $CXX --version
  - g++-4.8 --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
